// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxUBIJmjeLJ5xBOfmvAKhae21RE8_OoSc',
    appId: '1:361759897756:web:ed0812eff5abdb66c65559',
    messagingSenderId: '361759897756',
    projectId: 'cinemadb-app',
    authDomain: 'cinemadb-app.firebaseapp.com',
    storageBucket: 'cinemadb-app.firebasestorage.app',
    measurementId: 'G-9LKGN9PNW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfntEH7p1nctZWIF-N3RVv5ir-2OMOGX8',
    appId: '1:361759897756:android:ccee88a1c5badb05c65559',
    messagingSenderId: '361759897756',
    projectId: 'cinemadb-app',
    storageBucket: 'cinemadb-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk_3FEKeSLECwJ_YYNo2NGd9HltJy1HO0',
    appId: '1:361759897756:ios:ac113696eaf83376c65559',
    messagingSenderId: '361759897756',
    projectId: 'cinemadb-app',
    storageBucket: 'cinemadb-app.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk_3FEKeSLECwJ_YYNo2NGd9HltJy1HO0',
    appId: '1:361759897756:ios:ac113696eaf83376c65559',
    messagingSenderId: '361759897756',
    projectId: 'cinemadb-app',
    storageBucket: 'cinemadb-app.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxUBIJmjeLJ5xBOfmvAKhae21RE8_OoSc',
    appId: '1:361759897756:web:c5c2335233ee778ec65559',
    messagingSenderId: '361759897756',
    projectId: 'cinemadb-app',
    authDomain: 'cinemadb-app.firebaseapp.com',
    storageBucket: 'cinemadb-app.firebasestorage.app',
    measurementId: 'G-2VCN105XKH',
  );
}
